# Пути к библиотеке QT для различных компиляторов и платформ
# NOTICE: В случае отсутствия какой-либо сборки необходимо указать путь к любой существующей (чтобы избежать ошибок CMAKE)
# NOTICE: Собрать проект с отсутствующей сборкой QT таким образом не получится, но ошибок CMAKE не будет
set(QT_GNU_X86_DIR          "C:\\Qt\\5.9.9\\mingw53_32\\")
set(QT_GNU_X86_STATIC_DIR   "C:\\Qt\\5.9.9\\mingw53_32\\")
set(QT_GNU_X64_DIR          "C:\\Qt\\5.9.9\\mingw53_32\\")
set(QT_GNU_X64_STATIC_DIR   "C:\\Qt\\5.9.9\\mingw53_32\\")
set(QT_MSVC_X64_DIR         "C:\\Qt\\5.9.9\\msvc2017_64\\")
set(QT_MSVC_X64_STATIC_DIR  "C:\\Qt\\5.9.9\\msvc2017_32_static\\")
set(QT_MSVC_X86_DIR         "C:\\Qt\\5.9.9\\msvc2017_64\\")
set(QT_MSVC_X86_STATIC_DIR  "C:\\Qt\\5.9.9\\msvc2017_32_static\\")

# Выбор пути к библиотеке QT в зависимости от конфигурации
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(PLATFORM_BIT_SUFFIX STREQUAL "x86")
        if(QT_STATIC_LINK)
            set(QT5_DIR ${QT_GNU_X86_STATIC_DIR})
        else()
            set(QT5_DIR ${QT_GNU_X86_DIR})
        endif()
    else()
        if(QT_STATIC_LINK)
            set(QT5_DIR ${QT_GNU_X64_STATIC_DIR})
        else()
            set(QT5_DIR ${QT_GNU_X64_DIR})
        endif()
    endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    if(PLATFORM_BIT_SUFFIX STREQUAL "x86")
        if(QT_STATIC_LINK)
            set(QT5_DIR ${QT_MSVC_X86_STATIC_DIR})
        else()
            set(QT5_DIR ${QT_MSVC_X86_DIR})
        endif()
    else()
        if(QT_STATIC_LINK)
            set(QT5_DIR ${QT_MSVC_X64_STATIC_DIR})
        else()
            set(QT5_DIR ${QT_MSVC_X64_DIR})
        endif()
    endif()
endif()